Import basic libraries

In [1]:
import pandas as pd

import numpy as np

Import the Dataset

In [2]:
bank_df = pd.read_csv("Bank_Personal_Loan_Modelling.csv")
bank_df.head()

ID  Age  Experience  Income  ZIP Code  Family  CCAvg  Education  Mortgage  \
0   1   25           1      49     91107       4    1.6          1         0   
1   2   45          19      34     90089       3    1.5          1         0   
2   3   39          15      11     94720       1    1.0          1         0   
3   4   35           9     100     94112       1    2.7          2         0   
4   5   35           8      45     91330       4    1.0          2         0   

   Personal Loan  Securities Account  CD Account  Online  CreditCard  
0              0                   1           0       0           0  
1              0                   1           0       0           0  
2              0                   0           0       0           0  
3              0                   0           0       0           0  
4              0                   0           0       0           1

Show if the dataset has any missing values

In [3]:
bank_df.isna().sum().sort_values()

ID                    0
Age                   0
Experience            0
Income                0
ZIP Code              0
Family                0
CCAvg                 0
Education             0
Mortgage              0
Personal Loan         0
Securities Account    0
CD Account            0
Online                0
CreditCard            0
dtype: int64

Work on the experience column to remove negetive values using their absolute values

In [4]:
bank_df["Experience"].unique()

array([ 1, 19, 15,  9,  8, 13, 27, 24, 10, 39,  5, 23, 32, 41, 30, 14, 18,
       21, 28, 31, 11, 16, 20, 35,  6, 25,  7, 12, 26, 37, 17,  2, 36, 29,
        3, 22, -1, 34,  0, 38, 40, 33,  4, -2, 42, -3, 43], dtype=int64)

In [5]:
bank_df["Experience"] = abs(bank_df['Experience'])

In [6]:
bank_df["Experience"].unique()

array([ 1, 19, 15,  9,  8, 13, 27, 24, 10, 39,  5, 23, 32, 41, 30, 14, 18,
       21, 28, 31, 11, 16, 20, 35,  6, 25,  7, 12, 26, 37, 17,  2, 36, 29,
        3, 22, 34,  0, 38, 40, 33,  4, 42, 43], dtype=int64)

Models

A: Import the nessesary libiraries

In [7]:
# train_test_split
from sklearn.model_selection import train_test_split

# Logistic regression
from sklearn.linear_model import LogisticRegression

# K neirest neighbors
from sklearn.neighbors import KNeighborsClassifier

#confusion matrix
from sklearn.metrics import confusion_matrix

1: Logistic regression

In [8]:
# Set the target and feature variables
X = bank_df.drop("Personal Loan", axis=1).values

y = bank_df["Personal Loan"].values

# split the data

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [9]:
# Make the Logistic regression object
logreg_mdl = LogisticRegression()

# fit the model
logreg_mdl.fit(X_train, y_train)

# predect X_test
logreg_mdl_y_pred = logreg_mdl.predict(X_test)

# Get the Accuracy score
logreg_mdl_acc_score = logreg_mdl.score(X_test, y_test)

# Print the Accuracy score
print(f"The accuracy score for the logistic regression model = {logreg_mdl_acc_score}")

# Make the confusion matrix
logreg_mdl_conf_matrix = confusion_matrix(y_test, logreg_mdl_y_pred)

# print the confusion matrix
print(f"The confusion matrix: \n{logreg_mdl_conf_matrix}")

The accuracy score for the logistic regression model = 0.908
The confusion matrix: 
[[874  21]
 [ 71  34]]


C:\Users\ahmed\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


2: KNN

In [10]:
# Set the target and feature variables
X = bank_df.drop("Personal Loan", axis=1).values

y = bank_df["Personal Loan"].values

# split the data

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [11]:
for k in range(1, 21):
    # Make the KNeighborsClassifier object
    knn_mdl = KNeighborsClassifier(n_neighbors=k)

    # fit the model
    knn_mdl.fit(X_train, y_train)
    
    # predect X_test
    knn_mdl_y_pred = knn_mdl.predict(X_test)
    
    # Get the Accuracy score
    knn_mdl_acc_score = knn_mdl.score(X_test, y_test)
    
    # Print the Accuracy score
    print(f"The number of neibors = {k} and it's accuracy score = {knn_mdl_acc_score}")

The number of neibors = 1 and it's accuracy score = 0.872
The number of neibors = 2 and it's accuracy score = 0.893
The number of neibors = 3 and it's accuracy score = 0.89
The number of neibors = 4 and it's accuracy score = 0.896
The number of neibors = 5 and it's accuracy score = 0.896
The number of neibors = 6 and it's accuracy score = 0.895
The number of neibors = 7 and it's accuracy score = 0.895
The number of neibors = 8 and it's accuracy score = 0.895
The number of neibors = 9 and it's accuracy score = 0.895
The number of neibors = 10 and it's accuracy score = 0.895
The number of neibors = 11 and it's accuracy score = 0.895
The number of neibors = 12 and it's accuracy score = 0.895
The number of neibors = 13 and it's accuracy score = 0.895
The number of neibors = 14 and it's accuracy score = 0.895
The number of neibors = 15 and it's accuracy score = 0.895
The number of neibors = 16 and it's accuracy score = 0.895
The number of neibors = 17 and it's accuracy score = 0.895
The num

In [12]:
# Make the KNeighborsClassifier object
knn_mdl = KNeighborsClassifier(n_neighbors=5)

# fit the model
knn_mdl.fit(X_train, y_train)

# predect X_test
knn_mdl_y_pred = knn_mdl.predict(X_test)

# Get the Accuracy score
knn_mdl_acc_score = knn_mdl.score(X_test, y_test)

# Print the Accuracy score
print(f"The number of neibors = 5 and it's accuracy score = {knn_mdl_acc_score}")

# Make the confusion matrix
knn_mdl_conf_matrix = confusion_matrix(y_test, knn_mdl_y_pred)

# print the confusion matrix
print(f"The confusion matrix: \n{knn_mdl_conf_matrix}")

The number of neibors = 5 and it's accuracy score = 0.896
The confusion matrix: 
[[893   2]
 [102   3]]
